export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUI_PROJETO = 'EXCLUI_PROJETO'
export const DEFINE_PROJETOS = 'DEFINE_PROJETOS'

export const NOTIFICA = 'NOTIFICA'

export const DEFINIR_TAREFAS = "DEFINIR_TAREFAS"